
version: 2

models:
    - name: base_keywords
      description: |
        The `base_keywords` model contains the keywords of interest, their categories and associated regular expressions.
      columns:
        - name: keyword
          tests:
          - unique
          - not_null  

    - name: base_posts
      description: |
        The `base_posts` model contains metrics and dimensions pertaining to reddit posts and the flat text data by sentence.
      columns:
        - name: sentence_keyword_id
          tests:
          - unique
          - not_null  

    - name: stg_keyword_extraction
      description: |
        The `stg_keyword_extraction` model calculates metrics and dimensions pertaining to the keywords in text data.
      columns:
        - name: sentence_keyword_id
          tests:
          - unique
          - not_null  

    - name: keyword_extraction
      description: |
        The `keyword_extraction` model contains metrics and dimensions pertaining to the keywords identified in text data.
      columns:
          - name: keyword_sentence_id
            tests:
                - unique
                - not_null
